### ISSUE TITLE
More Responsive Continual Training

### ISSUE THREAD

**Issue by Demirrr** [dice-group/dice-embeddings#120]
Applying continual training on a pre-trained Keci Embeddings on YAGO4 results in following output:
```python
(dice) cdemir@felis:~/dice-embeddings$ python continual_training.py --path_experiment_folder "Yago4KeciEmbeddings"
/upb/users/c/cdemir/profiles/unix/cs/anaconda3/envs/dice/lib/python3.9/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (None)/charset_normalizer (3.2.0) doesn't match a supported version!
  warnings.warn(
ContinuousExecute starting...
namespace(logger=False, checkpoint_callback=None, enable_checkpointing=True, default_root_dir=None, gradient_clip_val=None, gradient_clip_algorithm=None, process_position=0, num_nodes=1, num_processes=None, devices=None, gpus=None, auto_select_gpus=False, tpu_cores=None, ipus=None, log_gpu_memory=None, progress_bar_refresh_rate=None, enable_progress_bar=True, overfit_batches=0.0, track_grad_norm=-1, check_val_every_n_epoch=1000000, fast_dev_run=False, accumulate_grad_batches=None, max_epochs=512, min_epochs=512, max_steps=-1, min_steps=None, max_time=None, limit_train_batches=None, limit_val_batches=None, limit_test_batches=None, limit_predict_batches=None, val_check_interval=None, flush_logs_every_n_steps=None, log_every_n_steps=50, accelerator=None, strategy=None, sync_batchnorm=False, precision=32, enable_model_summary=True, weights_summary='top', weights_save_path=None, num_sanity_val_steps=2, resume_from_checkpoint=None, profiler=None, benchmark=None, deterministic=True, reload_dataloaders_every_n_epochs=0, auto_lr_find=False, replace_sampler_ddp=True, detect_anomaly=False, auto_scale_batch_size=False, prepare_data_per_node=None, plugins=None, amp_backend='native', amp_level=None, move_metrics_to_cpu=False, multiple_trainloader_mode='max_size_cycle', stochastic_weight_avg=False, terminate_on_nan=None, path_dataset_folder='YAGO', save_embeddings_as_csv=False, storage_path='Experiments', model='Keci', optim='Adam', embedding_dim=100, num_epochs=1, batch_size=32000, lr=0.1, callbacks=[], backend='pandas', trainer='torchDDP', scoring_technique='NegSample', neg_ratio=1, weight_decay=0.0, input_dropout_rate=0.0, hidden_dropout_rate=0.0, feature_map_dropout_rate=0.0, normalization=None, init_param=None, gradient_accumulation_steps=0, num_folds_for_cv=0, eval_model=None, save_model_at_every_epoch=None, label_smoothing_rate=0.0, kernel_size=3, num_of_output_channels=2, num_core=32, seed_for_computation=0, sample_triples_ratio=None, read_only_few=None, p=0, q=1, auto_batch_finder=False, pykeen_model_kwargs={}, learning_rate=0.1, apply_reciprical_or_noise=False, full_storage_path='Yago4KeciEmbeddings', path_experiment_folder='Yago4KeciEmbeddings', num_entities=7648969, num_relations=99)
# of CPUs:32 | # of GPUs:2 | # of CPUs for dataloader:32
NVIDIA GeForce RTX 3090
NVIDIA GeForce RTX 3090
Initializing TorchDDPTrainer GPU	Took 0.0000 seconds|Current Memory Usage  564.04 in MB
Initializing Model...	Loading pre-trained model...
r:50	 p:0	 q:1
Took 5.1524 seconds|Current Memory Usage  3627.3 in MB

```

At each computational setup until the training starts, user should be informed. By looking at the last few lines, the current state of the computation is unclear.

**Comment by Demirrr** [comment]
```python
Took 385.0378 seconds|Current Memory Usage  2.9491e+04 in MB
Took 385.0380 seconds|Current Memory Usage  2.9491e+04 in MB
Took 388.5497 seconds|Current Memory Usage  2.7967e+04 in MB
Initializing Dataloader...	Took 0.0002 seconds|Current Memory Usage  2.7967e+04 in MB
Keci(
  (loss): BCEWithLogitsLoss()
  (normalize_head_entity_embeddings): IdentityClass()
  (normalize_relation_embeddings): IdentityClass()
  (normalize_tail_entity_embeddings): IdentityClass()
  (hidden_normalizer): IdentityClass()
  (input_dp_ent_real): Dropout(p=0.0, inplace=False)
  (input_dp_rel_real): Dropout(p=0.0, inplace=False)
  (hidden_dropout): Dropout(p=0.0, inplace=False)
  (entity_embeddings): Embedding(7648969, 100)
  (relation_embeddings): Embedding(99, 100)
  (q_coefficients): Embedding(1, 1)
)
   | Name                             | Type              | Params
------------------------------------------------------------------------
0  | loss                             | BCEWithLogitsLoss | 0     
1  | normalize_head_entity_embeddings | IdentityClass     | 0     
2  | normalize_relation_embeddings    | IdentityClass     | 0     
3  | normalize_tail_entity_embeddings | IdentityClass     | 0     
4  | hidden_normalizer                | IdentityClass     | 0     
5  | input_dp_ent_real                | Dropout           | 0     
6  | input_dp_rel_real                | Dropout           | 0     
7  | hidden_dropout                   | Dropout           | 0     
8  | entity_embeddings                | Embedding         | 764 M 
9  | relation_embeddings              | Embedding         | 9.9 K 
10 | q_coefficients                   | Embedding         | 1     
------------------------------------------------------------------------
764 M     Trainable params
0         Non-trainable params
764 M     Total params
3,059.627 Total estimated model params size (MB)
None

Training is starting 2023-07-24 12:51:48.336329...
Traceback (most recent call last):
  File "/data/upb/users/c/cdemir/profiles/unix/cs/dice-embeddings/continual_training.py", line 26, in <module>
    ContinuousExecute(args).continual_start()
  File "/data/upb/users/c/cdemir/profiles/unix/cs/dice-embeddings/dicee/executer.py", line 262, in continual_start
    self.trained_model, form_of_labelling = self.trainer.continual_start()
  File "/data/upb/users/c/cdemir/profiles/unix/cs/dice-embeddings/dicee/trainer/dice_trainer.py", line 135, in continual_start
    self.trainer.fit(model, train_dataloaders=train_loader)
  File "/data/upb/users/c/cdemir/profiles/unix/cs/dice-embeddings/dicee/trainer/torch_trainer_ddp.py", line 52, in fit
    torch.distributed.init_process_group(backend="nccl")
  File "/upb/users/c/cdemir/profiles/unix/cs/.local/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 900, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/upb/users/c/cdemir/profiles/unix/cs/.local/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 235, in _env_rendezvous_handler
    rank = int(_get_env_or_raise("RANK"))
  File "/upb/users/c/cdemir/profiles/unix/cs/.local/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 220, in _get_env_or_raise
    raise _env_error(env_var)
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set
```
After few minutes, the above execution led to `ValueError`. This stems from the fact that the initial model is trained via `torchrun`. 
Potential fix for this error:

1. `torchrun --standalone --nproc_per_node=gpu python ..` 
2. `python continual_training.py --trainer PL`

**Comment by Demirrr** [comment]
1. CL should be integrated into main.py and dice/run.py
2. continual_training.py should be removed

**Comment by Demirrr** [comment]
done
