### ISSUE TITLE
Fix needed examples/multi_hop_query_answering/benchmark.py

### ISSUE THREAD

**Issue by sshivam95** [dice-group/dice-embeddings#278]
In https://github.com/dice-group/dice-embeddings/blob/develop/examples/multi_hop_query_answering/benchmarking.py, the variable `path_dataset_folder` is being used which is deprecated. This fails the run of the benchmark file.

There is also an error occuring `RuntimeError: Tensors must have same number of dimensions: got 2 and 1`. Here is the full log stack:
```
Seed set to 0
Start time:2024-11-28 10:07:09.021328
*** Read or Load Knowledge Graph  ***
*** Reading KGs/UMLS/train.txt with Pandas ***
Reading with pandas.read_csv with sep ** s+ ** ...
read_with_pandas took 0.0037 seconds | Current Memory Usage  621.93 in MB
*** Reading KGs/UMLS/test.txt with Pandas ***
Reading with pandas.read_csv with sep ** s+ ** ...
read_with_pandas took 0.0011 seconds | Current Memory Usage  621.93 in MB
*** Reading KGs/UMLS/valid.txt with Pandas ***
Reading with pandas.read_csv with sep ** s+ ** ...
read_with_pandas took 0.0010 seconds | Current Memory Usage  622.1 in MB
Adding reciprocal triples to Train, e.g. KG:= (s, p, o) union (o, p_inverse, s)
Adding reciprocal triples to Validation, e.g. KG:= (s, p, o) union (o, p_inverse, s)
Adding reciprocal triples to Test, e.g. KG:= (s, p, o) union (o, p_inverse, s)
Concatenating data to obtain index...
Creating a mapping from entities to integer indexes...
preprocess_with_pandas took 0.0101 seconds | Current Memory Usage  623.9 in MB
Submit er-vocab, re-vocab, and ee-vocab via  ProcessPoolExecutor...
Preprocessing took: 0.267 seconds

------------------- Description of Dataset KGs/UMLS -------------------
Number of entities:135
Number of relations:92
Number of triples on train set:10432
Number of triples on valid set:1304
Number of triples on test set:1322
Entity Index:0.00001 in GB
Relation Index:0.00001 in GB

# of CPUs:20 | # of GPUs:0 | # of CPUs for dataloader:0
------------------- Train -------------------
Initializing TorchTrainer CPU Trainer...        Took 0.0022 secs | Current Memory Usage  624.72 in MB
Initializing Model...   Took 0.0027 secs | Current Memory Usage  625.86 in MB
Initializing Dataset... Took 0.0223 seconds
Number of datapoints: 1560
Took 0.0235 secs | Current Memory Usage  626.03 in MB
Took 0.0267 secs | Current Memory Usage  626.03 in MB
Initializing Dataloader...      Took 0.0005 secs | Current Memory Usage  626.03 in MB
Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.1
    maximize: False
    weight_decay: 0.0
)

  | Name                             | Type              | Params | Mode 
-------------------------------------------------------------------------------
0 | loss                             | BCEWithLogitsLoss | 0      | train
1 | normalize_head_entity_embeddings | IdentityClass     | 0      | train
2 | normalize_relation_embeddings    | IdentityClass     | 0      | train
3 | normalize_tail_entity_embeddings | IdentityClass     | 0      | train
4 | hidden_normalizer                | IdentityClass     | 0      | train
5 | input_dp_ent_real                | Dropout           | 0      | train
6 | input_dp_rel_real                | Dropout           | 0      | train
7 | hidden_dropout                   | Dropout           | 0      | train
8 | entity_embeddings                | Embedding         | 17.3 K | train
9 | relation_embeddings              | Embedding         | 11.8 K | train
-------------------------------------------------------------------------------
29.1 K    Trainable params
0         Non-trainable params
29.1 K    Total params
0.116     Total estimated model params size (MB)

Training is starting 2024-11-28 10:07:09.324289...
NumOfDataPoints:1560 | NumOfEpochs:20 | LearningRate:0.1 | BatchSize:1024 | EpochBatchsize:2
  0%|                                                                                                                                                                                                       | 0/20 [00:00<?, ?it/s]/home/sshivam/anaconda3/envs/dice/lib/python3.10/site-packages/lightning/pytorch/core/module.py:447: You are trying to `self.log()` but the `self.trainer` reference is not registered on the model yet. This is most likely because the model hasn't been passed to the `Trainer`
Epoch:20: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 15.67it/s, loss_step=0.07218, loss_epoch=0.14950]
Training Runtime: 1.312 seconds.

*** Save Trained Model ***
Took 0.0008 secs | Current Memory Usage  658.14 in MB
Total Runtime: 1.583 seconds
Evaluate DistMult on Train set: Evaluate DistMult on Train set
{'H@1': 0.6952645705521472, 'H@3': 0.8362730061349694, 'H@10': 0.9390337423312883, 'MRR': 0.7803371644384614}
Evaluate DistMult on Validation set: Evaluate DistMult on Validation set
{'H@1': 0.531441717791411, 'H@3': 0.7170245398773006, 'H@10': 0.88420245398773, 'MRR': 0.6474402578327663}
Evaluate DistMult on Test set: Evaluate DistMult on Test set
{'H@1': 0.5196671709531013, 'H@3': 0.7170953101361573, 'H@10': 0.8774583963691377, 'MRR': 0.6410769273862099}
Total Runtime: 3.034 seconds
/home/sshivam/Work/WDC/dice-embeddings/dicee/static_funcs.py:126: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  weights = torch.load(path_of_experiment_folder + f'/{model_name}', torch.device('cpu'))
General structure is ['e', ['r']] with name 1p. Number of queries generated: 100
General structure is ['e', ['r', 'r']] with name 2p. Number of queries generated: 100
General structure is ['e', ['r', 'r', 'r']] with name 3p. Number of queries generated: 100
General structure is [['e', ['r']], ['e', ['r']]] with name 2i. Number of queries generated: 100
General structure is [['e', ['r']], ['e', ['r']], ['e', ['r']]] with name 3i. Number of queries generated: 100
General structure is [['e', ['r', 'r']], ['e', ['r']]] with name pi. Number of queries generated: 100
General structure is [[['e', ['r']], ['e', ['r']]], ['r']] with name ip. Number of queries generated: 100
General structure is [['e', ['r']], ['e', ['r', 'n']]] with name 2in. Number of queries generated: 100
General structure is [['e', ['r']], ['e', ['r']], ['e', ['r', 'n']]] with name 3in. Number of queries generated: 100
General structure is [['e', ['r', 'r']], ['e', ['r', 'n']]] with name pin. Number of queries generated: 100
General structure is [['e', ['r', 'r', 'n']], ['e', ['r']]] with name pni. Number of queries generated: 100
General structure is [[['e', ['r']], ['e', ['r', 'n']]], ['r']] with name inp. Number of queries generated: 100
General structure is [['e', ['r']], ['e', ['r']], ['u']] with name 2u. Number of queries generated: 100
General structure is [[['e', ['r']], ['e', ['r']], ['u']], ['r']] with name up. Number of queries generated: 100
Loading...
Traceback (most recent call last):
  File "/home/sshivam/Work/WDC/dice-embeddings/examples/multi_hop_query_answering/benchmarking.py", line 69, in <module>
    entity_scores_for_each_query = pre_trained_kge.answer_multi_hop_query(query_type=query_type,
  File "/home/sshivam/Work/WDC/dice-embeddings/dicee/knowledge_graph_embeddings.py", line 585, in answer_multi_hop_query
    self.answer_multi_hop_query(query_type=query_type, query=i, tnorm=tnorm, neg_norm=neg_norm,
  File "/home/sshivam/Work/WDC/dice-embeddings/dicee/knowledge_graph_embeddings.py", line 790, in answer_multi_hop_query
    atom2_scores = torch.cat([atom2_scores, atom2_score], dim=0)
RuntimeError: Tensors must have same number of dimensions: got 2 and 1
```

**Comment by Demirrr** [comment]
Could you also share the command or code snippet to reporduce this issue ?

**Comment by sshivam95** [comment]
```
conda activate dice
python3 examples/multi_hop_query_answering/benchmarking.py
```

**Comment by Demirrr** [comment]
Thank you! @sshivam95 would you like to take over this issue ?

**Comment by sshivam95** [comment]
Issue resolved. Deleting all the `__pycache__` files and starting from fresh fixed it.
